### ISSUE TITLE
add support for `Pix *tesseract::TessBaseAPI::GetThresholdedImage()`

### ISSUE THREAD

**Issue by StephenHogg** [xiahongze/pysseract#16]
This one is potentially a little tricky but worthwhile. 

Before actually doing OCR on an image, Tesseract performs some pre-processing. This isn't always helpful, so the user may want to check what their image is being turned into by pre-processing if the results are inexplicably bad, for instance.

The `GetThresholdedImage()` method returns the image after pre-processing. The trick here is that it returns it as this `Pix *` object which is a struct that comes from Liblept. So we need to wrap that struct as well and find a way of converting the data embedded in it into (for example), a numpy array. 

@xiahongze got any thoughts?

**Comment by StephenHogg** [comment]
Actually this looks like it might be easier than it appears if we're happy to return a byte string rather than the underlying Leptonica object.

**Comment by xiahongze** [comment]
good work!
