### ISSUE TITLE
Add conda-forge and pypi integration

### ISSUE THREAD

**Issue by StephenHogg** [xiahongze/pysseract#9]

**Comment by StephenHogg** [comment]
pypi done, how much do we care about conda-forge?

**Comment by xiahongze** [comment]
Not, really. Unless we want to push osx binary?

**Comment by StephenHogg** [comment]
Tricky one. If we wanted to push an osx binary I'd do it through PyPI so that you always download from the same place regardless of OS. So if we were going to push to conda-forge, I'd probably want to put everything on there. 

So does this mean we should rename this issue to "work out OS X binary"?
